const mongoose = require('mongoose');

const signalSchema = new mongoose.Schema(
  {
    asset: {
      type: String,
      required: [true, 'Asset is required'],
      trim: true,
      // e.g. EUR/USD, BTC/USD, Gold, Apple
    },
    direction: {
      type: String,
      enum: ['BUY', 'SELL'],
      required: [true, 'Direction (BUY/SELL) is required'],
    },
    timeframe: {
      type: String,
      enum: ['30s', '1m', '2m', '5m', '15m', '30m', '1h'],
      required: [true, 'Timeframe is required'],
    },
    entryPrice: {
      type: Number,
      required: [true, 'Entry price is required'],
    },
    entryTime: {
      // When the user should open the trade (at least 1 min after signal is generated)
      type: Date,
      required: [true, 'Entry time is required'],
    },
    expiryTime: {
      // When the trade closes (entryTime + trade duration)
      type: Date,
      required: [true, 'Expiry time is required'],
    },
    confidence: {
      // Analyst confidence score 0–100
      type: Number,
      min: 0,
      max: 100,
      default: 70,
    },
    indicators: {
      // Supporting technical indicators used
      type: [String],
      default: [],
      // e.g. ['RSI', 'MACD', 'Bollinger Bands']
    },
    notes: {
      type: String,
      trim: true,
      default: '',
    },
    status: {
      type: String,
      enum: ['pending', 'active', 'expired', 'won', 'lost', 'skipped', 'cancelled'],
      default: 'pending',  // starts as pending until entryTime is reached
    },
    result: {
      type: String,
      enum: ['win', 'loss', 'draw', null],
      default: null,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // 'engine' = auto-generated by the signal engine | 'manual' = created by admin
    generatedBy: {
      type: String,
      enum: ['engine', 'manual'],
      default: 'manual',
    },
  },
  { timestamps: true }
);

// Auto-expire signals past their expiryTime
signalSchema.index({ expiryTime: 1 });

module.exports = mongoose.model('Signal', signalSchema);
